AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Metrics/LineLength:
  # Commonly used screens these days easily fit more than 80 characters.
  Max: 120
  Exclude:
    - "spec/**/*.rb"

# [codesmell]
Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
