HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Fri, 09 Aug 2019 10:52:36 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 20
Connection: close
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type, authorization, Origin, X-Requested-With, Content-Type, Accept
Vary: X-HTTP-Method-Override
Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
X-Content-Type-Options: nosniff
ETag: W/"14-GdU/Rwzl6jmbFjuKkYH3gQ"

{"status":"ENVIADO"}
